config/routes.rb
Rails.application.routes.draw do

  root :to => 'homepage#index'

  resources :pictures
  resources :profiles

  post '/pictures' => 'pictures#create'
  get '/beardometer' => 'pictures#index'

  get '/.well-known/acme-challenge/:id' => 'homepage#letsencrypt'

end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id         :integer          not null, primary key
#  image      :text
#  anger      :decimal(, )
#  contempt   :decimal(, )
#  disgust    :decimal(, )
#  fear       :decimal(, )
#  happiness  :decimal(, )
#  neutral    :decimal(, )
#  sadness    :decimal(, )
#  surprise   :decimal(, )
#  created_at :datetime
#  updated_at :datetime
#



class Picture < ActiveRecord::Base
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id              :integer          not null, primary key
#  name            :string
#  image_url       :string
#  sponsorship_url :string
#  message         :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Profile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def index
	end

	def letsencrypt
		render text: "#{homepage_params[:id]}.#{ENV["LETSENCRYPT_RESPONSE"]}"
	end

	private
	def homepage_params
		params.permit(:id)
	end
end

app/controllers/pictures_controller.rb
# == Schema Information
#
# Table name: pictures
#
#  id         :integer          not null, primary key
#  image      :text
#  anger      :decimal(, )
#  contempt   :decimal(, )
#  disgust    :decimal(, )
#  fear       :decimal(, )
#  happiness  :decimal(, )
#  neutral    :decimal(, )
#  sadness    :decimal(, )
#  surprise   :decimal(, )
#  created_at :datetime
#  updated_at :datetime
#

class PicturesController < ApplicationController

	def index
  		@pictures = Picture.all
	end

	def create
  		@picture = Picture.new picture_params
  		responses = Cloudinary::Uploader.upload params[:picture][:image]
  		@image1 = responses["url"]

  		r = HTTParty.post("https://api.projectoxford.ai/emotion/v1.0/recognize", :headers => { "Content-Type" => "application/json", "Ocp-Apim-Subscription-Key" => "043cf24268dc4468b1a056991cb1b70f" }, :body => {"url" => @image1 }.to_json)
  		if r.blank?
			render js: "window.alert('This picture has no faces please retake photo');"
		elsif r.length > 1
			render js: "window.alert('Only one face is allowed, please retake photo');"
		else
			@picture.image = responses["url"]
		  @picture.anger = r[0]['scores']['anger']
			@picture.contempt  = r[0]['scores']['contempt']
			@picture.disgust  = r[0]['scores']['disgust']
			@picture.fear  = r[0]['scores']['fear']
			@picture.happiness  = r[0]['scores']['happiness']
			@picture.neutral = r[0]['scores']['neutral']
			@picture.sadness = r[0]['scores']['sadness']
			@picture.surprise = r[0]['scores']['surprise']

			@picture.save

			render js: "window.location.href = '#{picture_path(@picture.id)}'"
		end

    end

	def show
		@picture = Picture.find params[:id]
	end

	def homepage
	end


	private
	def picture_params
		params.require(:picture).permit(:id, :image, :anger, :contempt, :disgust, :fear, :happiness, :neutral, :sadness, :surprise)
	end
end

app/controllers/profiles_controller.rb
# == Schema Information
#
# Table name: profiles
#
#  id              :integer          not null, primary key
#  name            :string
#  image_url       :string
#  sponsorship_url :string
#  message         :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class ProfilesController < ApplicationController

  def index
      @profiles = Profile.all
  end

  def create
     @profile = Profile.new(profile_params)
       response = Cloudinary::Uploader.upload params[:profile][:image_url]
    @profile.image_url = response["url"]
     if @profile.save
       render js: "window.location.href = '#{profile_path(@profile.id)}'"
     end
   end

  def show
		@profile = Profile.find params[:id]
	end


  private
  def profile_params
    params.require(:profile).permit(:image_url, :name, :sponsorship_url, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/views/home/index.html.erb
<div id="janu-container">
    <!-- Hero logo and intro heading -->
    <%= image_tag 'logo_transparent.png', id: 'janu-logo', alt: 'janubeard logo'%>
    <h1>Beardify yourself!<br />Get hairy with our Beard Generator!</h1>

    <!-- Intro paragraphs -->
    <p>Become bewhiskered, stubbly, shaggy, bushy, woolly, furry, fleecy and bristly - all in the name of <span>raising money for kids suffering from cancer.</span></p>
    <p>Janubeard is the world’s largest beard harmonisation event, with one unifying factor: respect and nurture of the beard for the month of January.</p>

    <!-- Beardify button link -->
    <!-- Unknown reason why this button is hidden. Link created instead -->
    <div id="beardify-link-section">
      <a id="beardify-link" href="/pictures">Beard me up!</a>
    </div>

    <div id="black-section-divider"><p>Here is how we help...</p></div>

    <!-- Synopsis of child Lulu-->
    <%= image_tag 'lulu.jpg', alt: 'photo of Lulu, a young child who was diagnosed with cancer'%>
    <p>This little beauty is Lulu. At 8-months old she was diagnosed with a type of childhood cancer called Neuroblastoma.</p>
    <p>Lulu is now 6 years old, but like so many other kids with cancer, Lulu needs more research. <a href="http://bit.ly/Lulus_Story" target="_blank">Read Lulu’s story</a></p>

    <!-- Donation section block -->
    <div id="donation-block">
      <h2>Even a small amount makes a big difference!</h2>
      <p>Donate now to help kids with cancer</p>
      <div id="donation-options">
        <button class="donation-button">$10</button>
        <button class="donation-button">$25</button>
        <button class="donation-button">$200</button>
        <button class="donation-button">$500</button>
        <button class="donation-button">$8,000</button>
      </div>
      <h3>Spread the word</h3>
      <p>to help kids with cancer...</p>
      <div id="spread-word-banner">
        <a href="https://www.facebook.com/Janubeard/" target="_blank"><%= image_tag 'facebook_red.png', class: 'spread-word-icons', alt: 'janubeard facebook'%></a>
        <a href="https://twitter.com/janubeard" target="_blank"><%= image_tag 'twitter_red.png', class: 'spread-word-icons', alt: 'janubeard twitter'%></a>
        <a href="https://www.instagram.com/janubeard/" target="_blank"><%= image_tag 'instagram_red.png', class: 'spread-word-icons', alt: 'janubeard instagram'%></a>
        <!-- linkedin icon hidden until needed -->
        <!-- <a href="" target="_blank"><%= image_tag 'linkedin.png', class: 'spread-word-icons', alt: 'linkedin'%></a> -->
      </div>
    </div>

    <!-- Beardify action shots section block -->
    <div id="action-shots-section">
      <h3>Beard up for the kids!</h3>
      <div id="action-shots-gallery">
        <%= image_tag 'p1.jpg', alt: 'bearded human'%>
        <%= image_tag 'p2.jpg', alt: 'bearded human'%>
        <%= image_tag 'p3.jpg', alt: 'bearded human'%>
      </div>
    </div>
  </div> <!-- end container -->

</body>

</html>

app/views/homepage/index.html.erb
<div id="janu-container">

  <!-- Hero logo and intro heading -->
  <%= image_tag "logo_transparent.png", id: "janu-logo", alt: 'janubeard logo'  %>
  <h1>Get hairy with our Beardometer</h1>

  <!-- Intro paragraphs -->
  <p>Become bewhiskered, stubbly, shaggy, bushy, woolly, furry, fleecy and bristly - all in the name of <span>raising money for kids suffering from cancer.</span></p>
  <p>Janubeard is the world’s largest beard harmonisation event, with one unifying factor: respect and nurture of the beard for the month of January.</p>

  <!-- Beardify button link -->
  <!-- Unknown reason why this button is hidden. Link created instead -->
  <div id="beardify-link-section">
    <a id="beardify-link" href="/beardometer">Beard me up!</a>
  </div>

  <div id="black-section-divider"><p>Here is how we help...</p></div>

  <!-- Synopsis of child Lulu-->
  <%= image_tag "lulu.jpg", alt: 'Photo of Lulu, a young child who was diagnosed with cancer'  %>
  <p>This little beauty is Lulu. At 8-months old she was diagnosed with a type of childhood cancer called Neuroblastoma.</p>
  <p>Lulu is now 7 years old, but like so many other kids with cancer, Lulu needs more research. <a href="http://bit.ly/Lulus_Story" target="_blank">Read Lulu’s story</a></p>

  <!-- Donation section block -->
  <div id="donation-block">
    <h2>Even a small amount makes a big difference!</h2>
    <p>Donate now to help kids with cancer</p>
    <div id="donation-options">
      <a href="https://donate.ccia.org.au/campaign/16/janubeard" class="donation-button">Donate Now</a>
    </div>
    <h3>Spread the word</h3>
    <p>to help kids with cancer...</p>
    <div class="social-likes">
    	<div class="facebook" title="Share Beardometer on Facebook">Facebook</div>
    	<div class="twitter" data-via="sonny_mai" title="Share Beardometer on Twitter">Twitter</div>
    	<div class="plusone" title="Share Beardometer on Google+">Google+</div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beardometer</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="userpage" content="Your amazing photo yo">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= yield :head %>
  <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
</head>
<body>
  <div class="nav-bar">
    <!-- Hamburger menu -->
    <a class="burger-menu" href="">
      <div class="burger-icon"> <!-- burger icon strips -->
        <div class="burger-strips"></div>
        <div class="burger-strips"></div>
        <div class="burger-strips"></div>
      </div>  <!-- end burger icon strips -->

      <!-- text 'MENU'' for burger menu not included, UX decision -->
      <!-- <p>MENU</p> -->
    </a> <!-- end Hamburger menu -->
    <a href="/">
      <%= image_tag 'nav_logo.png', class: 'nav-logo' %>
    </a>

    <a href="" target="_blank"></a>

  </div> <!-- end nav-bar -->

  <%= yield %>

</body>
</html>

app/views/pictures/index.html.erb
<div class="container">

  <div class="video-container"
    data-shutter-ogg="<%= image_path('shutter.ogg')%>"
    data-shutter-mp3="<%= image_path('shutter.mp3')%>">

      <video autoplay="true"></video>
      <%= image_tag 'beard0.png', class: 'beard-image' %>
      <canvas id="beard-canvas"></canvas>
  </div>

  <div style="display: none;" id="beards">
    <%= image_tag "beard0.png" %>
    <%= image_tag "beard1.png" %>
    <%= image_tag "beard2.png" %>
    <%= image_tag "beard3.png" %>
    <%= image_tag "beard4.png" %>
    <%= image_tag "beard5.png" %>
  </div> <!-- end beards -->

</div> <!-- end container -->

<div class="bottom-bar">
  <button id="prev-beard"><%= image_tag "arrow_right.png", alt: "previous beard" %></button>
  <button id="snapshot"><%= image_tag "camera_white.png", alt: "take camera snapshot" %></button>
  <button id="retake-button" style="display: none;">Retake</button>
  <div id="share-banner" style="display: none;"> <!-- share-banner div holds all icons -->
    <p id="share-beard">Share</p>
    <a id="share-facebook" href="" target="_blank"><%= image_tag "facebook_white.png", alt: "share on facebook", class: "share-icons" %></a>
  </div> <!-- end share-banner div -->
  <button id="save-button" style="display: none;">Save</button>
  <button id="next-beard"><%= image_tag "arrow_left.png", alt: "next beard" %></button>
</div>
<!-- end button-container -->

app/views/pictures/show.html.erb
<h1>Your emotions are now detected please see below! </h1>
<%= image_tag @picture.image %>
<p>Anger  :<%= @picture.anger %></p>
<p>Disgust :<%= @picture.disgust %></p> 
<p>Fear :<%= @picture.fear %></p> 
<p>Happiness :<%= @picture.happiness %></p> 
<p>Neutral :<%= @picture.neutral %></p> 
<p>Sadness :<%= @picture.sadness %></p>
<p>Surprise : <%= @picture.surprise %></p>



 <div id='error-div'></div>

app/views/profiles/show.html.erb
<% content_for :head do %>
  <meta property="og:url"           content="<%= profile_url(@profile) %>" />
	<meta property="og:type"          content="website" />
	<meta property="og:title"         content="The Beardometer Has Spoken." />
	<meta property="og:description"   content="I've bearded up for kids with cancer." />
	<meta property="og:image"         content="<%= @profile.image_url %>" />
<% end %>

<div class="profile-container">
<div class="heading">
  <p>The Beardometer Has Spoken.</p>
</div>

<div class="picture">
  <%= image_tag @profile.image_url %>

  <p>Share this beard & help raise funds for kids with cancer www.janubeard.org</p>
  <div class="social">
  <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="fb-share-button"
      data-size="large"
      data-href=<%= profile_url(@profile) %>
      data-layout="button_count">
    </div>
    <a href="https://twitter.com/share" class="twitter-share-button"
        data-size="large"
        data-text="The Beardometer Has Spoken: I've bearded up for kids with cancer."
        data-url="<%= profile_url(@profile) %>"
        data-hashtags="janubeard"
        data-via="janubeard">Tweet</a>
  </div>
</div>

<div class="bottom-bar">
  <a id="beardify-link" href="/beardometer">
    <%= image_tag "camera_white.png", alt: "take camera snapshot" %>
    Beard me up!
  </a>
</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>